### ISSUE TITLE
進捗1

### ISSUE THREAD

**Issue by tryuuu** [tryuuu/my-computeclass#1]
### やりたいこと
起動したいインスタンスタイプのNodeをカスタムリソースで優先順位づけする形で定義できるようにして、Nodeがスケールするときにその優先順位を守りながらスケールするようにする(Nodeのオートスケール自体はClusterAutoscalerが行うが、その際に起動するNodeのインスタンスタイプをカスタムリソース・カスタムコントローラで制御する)
### CRDの設定
```
spec:
  description: MyComputeClassSpec defines the desired state of MyComputeClass.
  properties:
    properties:
      items:
        properties:
          machineFamily:
            type: string
          priority:
            type: integer
          spot:
            type: boolean
        required:
        - machineFamily
        - priority
        type: object
      type: array
  required:
  - properties
```

### 優先度順
- [x] webhookを利用するために証明書の設定などをしておく。
- [x] カスタムリソースの適用時と新たなNode起動時に、全てのNodeに対してPodが勝手にスケジューリングされないようtaintを付与する(付与済みの場合重複して付与しないよう注意する)
```
{
  "effect": "NoSchedule",
  "key": "my-compute-class",
  "value": "n2"
}
```
- [x] Pod作成時にMutating Admission Webhookが呼び出されるようにし、priorityが最も高いInstanceTypeのNodePoolに関するTolerationをPodに付与する。
```
kubectl get pods nginx -o json | jq '{name: .metadata.name, tolerations: .spec.tolerations}'
tolerations:
  - effect: NoSchedule
    key: my-compute-class
    operator: Equal
    value: n2
```
- [x] ClusterAutoScalerのデフォルト挙動だとtaintsがあってもe2に優先的にスケジューリングされてしまうので、 それを避けるために[カスタムマシンファミリー](https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning?hl=ja#custom_machine_family)を利用し、RequiredDuringSchedulingIgnoredDuringExecutionを設定してデフォルトのe2ではなくn2やn2dなど、カスタムリソースで定義しているマシンファミリーのNodeを起動するようClusterAutoScalerに指示する
- [x] taints/tolerationsにより、カスタムリソースで定義している最優先のmachineFamilyのNodeにスケジューリングされることを確認する
```
k get pods -o wide 
NAME    READY   STATUS    RESTARTS   AGE     IP           NODE                                                  NOMINATED NODE   READINESS GATES
nginx   1/1     Running   0          5m19s   172.17.2.2   gke-sreake-intern-tr-nap-n2-standard--4fd12531-7b6q   <none>           <none>
```
Nodeの自動プロビジョニングを無効にしている場合、n2dのNodeが優先的に起動している
```
kubectl get nodes -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.metadata.labels.cloud\.google\.com/gke-nodepool}{"\n"}{end}'
gke-sreake-intern-tr-nap-e2-standard--081369f5-l249     nap-e2-standard-2-7oucysnv
gke-sreake-intern-tr-sreake-intern-tr-093ebee6-s4nq     sreake-intern-tryu-np-n2
gke-sreake-intern-tr-sreake-intern-tr-093ebee6-t8w9     sreake-intern-tryu-np-n2
gke-sreake-intern-tr-sreake-intern-tr-093ebee6-vl64     sreake-intern-tryu-np-n2
gke-sreake-intern-tr-sreake-intern-tr-093ebee6-wsdc     sreake-intern-tryu-np-n2
gke-sreake-intern-tr-sreake-intern-tr-f45cc4a8-rfxr     sreake-intern-tryu-np-n2d
```
