### ISSUE TITLE
仕様のまとめ

### ISSUE THREAD

**Issue by tryuuu** [tryuuu/my-computeclass#2]
CRD:
```
properties:
  priorities:
    description: A list of instance types and their priorities.
    type: array
    items:
      type: object
      properties:
        instanceType:
          description: The instance type for the Node which users want to use.
          type: string
        priority:
          description: The priority of the instance type.
          type: integer
        spot:
          description: The spot instance flag.
          type: boolean
        required:
        - instanceType
        - priority
```
